### PR TITLE
Clean-up docs assets.

### PR DESCRIPTION
**Pull request by anolson**
JIRA Story:
https://teamtreehouse.atlassian.net/browse/EI-133

This adds better organization and improves the workflow around the `docs` asset generation.

* Move , `docs/css` `docs/img` `docs/js` into `docs/assets`
* Modify the `docs:css` gulp task to concat and minify all styles (sass and css)
* Pull prism styles into `docs/src/css`
* Add a `docs:js` gulp task to concat and minify all JS
* Simplify `nav.js` and remove the hardcoded navigation items.
* Rework the `tab.js` code and remove the dependency on jQuery

Because all images moved from `docs/img` to `docs/assets/img`, anything that references the old path needs to be updated.  I believe that I've updated all the references in this branch. If this ships before #5, we might need to update some of the image paths there as well.

### CODE REVIEW

**Comment by hopearmstrong** [comment]
@anolson What's the difference between docs/assets/css/ and docs/css? They both have a styleguide.css file. Same question regarding the docs/assets/img and docs/img folders.

Should the docs/css and docs/img folders be deleted, or are they there for a purpose?

**Comment by anolson** [comment]
> Should the docs/css and docs/img folders be deleted, or are they there for a purpose?

Hmm, everything in docs/css + docs/img should have moved to docs/assets.  I'm not sure why they're hanging around.  

Let's try this:
* Try deleting `docs/css` + `docs/img` locally
* Run `yarn run gulp build` and/or `yarn run gulp serve`
* See if either of those directories show up again

**Comment by anolson** [comment]
@hopearmstrong  It looks like the `docs` directory structure is correct on GH:
https://github.com/treehouse/email-style-guide/tree/clean-up-assets/docs

I wonder if you had Jekyll running in the background when you pulled this branch.  If so, it's possible that could have re-generated CSS in `docs/css` ¯\\\_(ツ)_/¯

**Comment by hopearmstrong** [comment]
@anolson Yeah, that must have been what happened. Somehow I was seeing an in-between state. Hm. Anyway, looks correct on GH so I think this is good to go.

**Review by hopearmstrong — APPROVED** [review]

**Pull request merged**
