### PR TITLE
Add automated testing.

### PR DESCRIPTION
**Pull request by anolson**
### Why

It would be nice to automatically check for broken links, missing images, and other inconsistencies before merging.

### What

This PR adds the `html_proofer` gem that checks for broken links, missing images, and other inconsistencies.  I also moved all the include directories in `atoms` and `molecules` into  `atoms/_includes` and `molecules/_includes`.  This  keeps those directories from ending up in  `docs/_site` and from being processed by `html_proofer`.

Add automated testing:

* Dead link checking, etc (with html-roofer)
* ~Sass Linting~

**Running:**
```
$ yarn build
$ bin/test
```

**Todo List:**
- [x] Update `README.md`
- [x] Update `yarn build` to build the `docs`
- [x] Add `bin/test` + `yarn` config
- [x] Figure out what to do with inaccessible links (GitHub + Invision)
- [x] Configure Codeship
- [ ] ~Fix the `#` and `{{ unsubscribe_url }}` links~
- [ ] ~Add Sass Linting~

### CODE REVIEW

**Review by thinmatt — APPROVED** [review]
👍

**Comment by hopearmstrong** [comment]
@anolson Amazing. Did you add all the features listed on https://github.com/gjtorikian/html-proofer or cherry pick only the broken links and missing images features? Specifically, the HTML validation and image ALT tag checking would be super helpful.

**Comment by anolson** [comment]
> Specifically, the HTML validation and image ALT tag checking would be super helpful.

Oh, good call.  We should be doing alt tag checking, but I'll need to turn on HTML Validation.

**Comment by anolson** [comment]
@hopearmstrong I turned on HTML Validation with 0e37dba.

```
Running ["ImageCheck", "ScriptCheck", "HtmlCheck", "LinkCheck"] on ["docs/_site"] on *.html... 


Checking 113 external links...
Ran on 39 files!


HTML-Proofer finished successfully.
```

**Pull request merged**
