### PR TITLE
Email Template & Atom Class Refinement

### PR DESCRIPTION
**Pull request by thinmatt**
This PR originally started as an experiment to try and simplify the table structure of the b2b email.

After digging in to that, it turned in to an exploration to test the atomic class system for the email css framework. Good news is that it worked. The bad news is that it required me to rework a bunch of the utility classes.

The PR itself is pretty messy, but should provide a good starting point for defining molecules

### CODE REVIEW

**Comment by hopearmstrong** [comment]
Thanks, @thinmatt. I pushed some changes to knock out a few of the small bugs I noticed while testing in Email on Acid. The remaining bugs are noted on this [testing spreadsheet](https://docs.google.com/a/teamtreehouse.com/spreadsheets/d/1E3Ukfj2AeoWqN4FSmiGybLpC45czv-D_x32Vgni7FTU/edit?usp=sharing), and I'll work on fixing those tomorrow.

Other to-dos that I can think of:
- [ ] add in the media queries
- [ ] look into adding bigger padding classes for the cards (it's more narrow now)
- [ ] @anolson, can you get the template builder to compile an external CSS file? it was including the CSS when it was in the template's HTML file, but now that we're linking to an external CSS file it looks like it's not adding it.

**Comment by thinmatt** [comment]
I updated 2 things this morning:

- Extracted the border color from the main button class and added it to the color specific button class
- Also added a base padding utility class so we can apply the 7% padding when necessary. You can all it with `.esg-p-base`. Works with the `-t` and other side suffixes as well.

**Comment by hopearmstrong** [comment]
@anolson Heya, can we sync on this tomorrow and go over the conflicts? I'm adding content to the guide on the "adding-examples" branch too, and I'm hoping we can merge that in as well so we can consolidate these branches and get the GitHub page updated. :-D

**Review by anolson — APPROVED** [review]
👍

**Pull request merged**
