### PR TITLE
Create a process for building email templates.

### PR DESCRIPTION
**Pull request by anolson**
### Why

Designers will be adding new email templates on a fairly regular basis.  We need to develop a process around adding and updating templates.  Inlining CSS and minifying HTML is a pretty common task when for HTML emails, and we'd like to have an automated way of doing this.

### What

This adds a `gulp` task for building email templates from `src/templates`.  Right now that inlines CSS and minifies HTML, but we can add additional steps as needed.  There is also a new task for building templates in `docs/templates` (without minification).

#### Building templates

To build all the `docs` and `src` use:

```
$ yarn build
```

There are also individual `template` gulp tasks:

```
$ yarn run gulp templates
$ yarn run gulp docs:templates
```

**Note: Running `yarn run gulp src` and `yarn run gulp docs` will also trigger their respective `template` tasks.**

### Todo

- [x] Use `gulp-inline-css` plugin 
- [x] Look for templates in `src/templates` and output to `dist/templates`
- [x] Minify HTML?
- [x] Pull examples into `docs/src/templates` and add to build
- [x] Add the ability to preview templates
- [x] Update `README.md` with docs for adding templates

### CODE REVIEW

**Comment by anolson** [comment]
@hopearmstrong @thinmatt This is ready for review when you have a chance.

First run:

```
$ bin/setup
```

Then, a few things to check:

* Are the instructions the README.md easy to follow?
* Try changing a template in `src/templates` and previewing those changes in your browser.

**Comment by hopearmstrong** [comment]
@anolson Hey Andrew, I'm getting an error trying to run Jekyll. Might be a dependencies problem on my part? Let's Screenhero tomorrow when you have a moment.

Looking at the files, it makes sense. I was confused at first about where the output goes, but now I see that in the To Do list on here. The src/dist workflow is probably common, but it wasn't obvious from my perspective. So, it'd help to clarify that in the README- the dist/templates and the docs/src/templates outputs.

**Comment by anolson** [comment]
> So, it'd help to clarify that in the README- the dist/templates and the docs/src/templates outputs.

Thanks, I'll clarify that. 👍

**Comment by anolson** [comment]
@hopearmstrong Can you take a look at the `README.md` and see if that helps clarify things.

**Review by hopearmstrong — APPROVED** [review]
This looks great, thanks Andrew!

**Pull request merged**
